### ISSUE TITLE
2 tests failed

### ISSUE THREAD

**Issue by arafesthain** [Szandor72/logger#9] opened 2020-07-27 09:54 UTC
![image](https://user-images.githubusercontent.com/13768869/88529037-b811b600-cfff-11ea-857a-a0d5c716b2da.png)

- sendLog_Success 
&
- sendLog_UserBasedLogging_Success

In both assert failed on :
`System.assertEquals(1, entries.size(), 'One Entry saved');`

**Comment by Szandor72** [comment] 2020-07-31 06:49
duplicate of #7

**Closed as completed by Szandor72** 2020-07-31 06:49 UTC
Labels: duplicate
